### ISSUE TITLE
Doesn't Notify When The AppSpan Application is closed.

### ISSUE THREAD

**Issue by vatsalcshah** [aliceblack/AppSpanAndroid#1]
When I leave the AppSpan App Open in Recents , the App notifies me that the limit has exceeded but when I close the app from recents ,the app doesn't send notifications.

**Comment by aliceblack** [comment]
Hi vatsalcshah, app has been tested on
- Android P, 9
- Android Nougat, 7.1.2
- Android Marshmallow, 6.0.1
and the notification service seems to be ok, on wich version of Android are you experiencing the problem?
Thanks for your feedback :relaxed:
